WSCPE: Fix `AnalizarCPE` method
- Changes in `ConsultarCPEAutomotor`, Web Service remove `fechaVencimiento` field

Error:

    KeyError: fechaVencimiento

Signed-off-by: Nicolás Sandoval <nicolassandovalunm@gmail.com>