Remove win32 python automation due DLL conflict
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
ImportError: Module use of python310.dll conflicts with this version of Python.
```